### ISSUE TITLE
Y create this?

### ISSUE THREAD

**Issue by hamuelxd12** [jjuliano/bato#11]
No one asked for this. Filipinos know English. -_-

**Comment by KBPsystem777** [comment]
Dude it’s FREE to open source lol

**Comment by MKThayn** [comment]
1. Not all Filipinos speak English... statistically only about 30% can be considered high proficiency. From my three years (plus) I would say that number should be lower.

2. Malaking tulong ito sa paguuswag sa wikang Filipino at ang pagunlad ng kaisipang Filipino. Oo naman malaking kalamangan kung mahusay kang mag-ingles pero mas pakinabang sa Filipinas kung may sariling mga wika at kultura. Isang scripting language ay isang napakagandang ambag sa sanhi niyon. ;)

**Comment by hamuelxd12** [comment]
You don't need to be fluent in English to use an English programming
language. There are only a few words you need to remember like the keywords
and the few easy to understand methods.

If you want, you can write your own functions and variables in Filipino.
Without requiring to be using a strange programming language.

**Comment by MKThayn** [comment]
You are correct. Lots of non-english speakers/non-native english speakers learn programming languages. The point I was getting at however was that small things like this project is a very very small step forward for the Filipino language and Filipino peoples. Sure, there are plenty of pinoys that can program but there are far less that can read a 900 page manual on Javascript. The key principle I like to address is the showcasing of what Wikang Filipino can do. Especially in times like this when poorer/developing countries are exerting extra efforts to acquiring English in the name of globalization but at the cost of identity and history. A language is a body of ideas, therefore, you can technically do anything you want in any language you want... All it takes is one person who asks himself simple questions like “What if we made Ruby in Filipino?” In order to get the ball rolling.

**Comment by hamuelxd12** [comment]
Your idea is right. Tho, I'm not with you with some of it. (Like the part
where you said that unifying with an international language costs
identity.) But sure, language might be limited, but it should be able to
morph depending on the needs of its users. So, go for it. Good luck and I
wish the best for this programming language.

**Comment by MKThayn** [comment]
And thank you for the discussion. If you’d like to chat more on programming, languages, or culture shoot me a pm.

**Comment by jjuliano** [comment]
> You don't need to be fluent in English to use an English programming language. There are only a few words you need to remember like the keywords and the few easy to understand methods. If you want, you can write your own functions and variables in Filipino. Without requiring to be using a strange programming language.
> […](#)

It is created as an inspiration to teach "only" those who are deserving, the unfortunate poor that can't meet the status quo of those educated Filipino "kuno" standards.

It is intended to teach farmers, garbage collectors, fisherman, carpenters, sapatero, the common poor Filipinos, the masses, the basic and advance concepts of programming.

AND it is designed so that when they learned Bato, they'll learn Ruby better than any educated Filipino.

Because Bato speaks the language of their heart, their mother tongue, which gives them better understanding of any advanced programming concepts BY HEART.

I don't need to justify why I created Bato to everyone, but I can justify to you that If I can teach one poor Filipino programming, their lives will be better.

I don't care if you don't want to use it, then don't use it. Bato is not for every Filipino, if it doesn't work for you, then it's not for you.

**Comment by GrpeApple** [comment]
This can also improve my native Filipino (I do not know why I suck at it)
